import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Utility scripts:
    "scripts/**",
    // GSD tooling — CommonJS CLI files, not app source:
    ".claude/**",
    // Compiled service worker bundle (generated by Serwist):
    "public/sw.js",
  ]),
]);

export default eslintConfig;
